version: '3.5'

services:
  api1:
    network_mode: host
    image: docker.io/library/rinha-de-backend-2023q3-java-spring:0.0.1-SNAPSHOT
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.75GB'
    environment:
      SERVER_PORT: 8001
      DB_HOST: localhost
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: rinhadb

  api2:
    network_mode: host
    image: docker.io/library/rinha-de-backend-2023q3-java-spring:0.0.1-SNAPSHOT
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.75GB'
    environment:
      SERVER_PORT: 8002
      DB_HOST: localhost
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: rinhadb

  db:
    network_mode: host
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.75GB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinhadb
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c 'max_connections=150'

  cache:
    network_mode: host
    hostname: cache
    image: redis:latest
    command: [ "redis-server", "--appendonly", "no", "--save ''" ]
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  nginx:
    network_mode: host
    image: nginx:latest
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.25GB'
